SPG/Controllers/parceleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Security.Claims;
using SPG;

namespace SPG.Controllers
{
    [Authorize]
    public class parceleController : Controller
    {
        public int DobaviID()
        {
            int IdUsera = Int32.Parse(User.Identity.Name);
            return IdUsera;
        }

        private Entities db = new Entities();
        
        // GET: parcele
        public ActionResult Index()
        {
            var userId = DobaviID();
            var parcele = db.parcele.Include(p => p.gospodarstva).Include(p => p.gradovi)
                .Where(p => p.id_korisnika == userId);
            ViewData["Parcele"] = parcele.ToList();
            ViewData["Farme"] = db.farme.Where(f => f.parcele.id_korisnika == userId).ToList();
            ViewData["Oranice"] = db.oranice.Where(f => f.parcele.id_korisnika == userId).ToList();

            return View();
        }

        // GET: parcele/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            parcele parcele = db.parcele.Find(id);
            var userId = DobaviID();
            if (parcele == null || parcele.id_korisnika != userId)
            {
                return HttpNotFound();
            }
            ViewData["Farme"] = db.farme.Where(f => f.parcele.id == id).ToList();
            ViewData["Oranice"] = db.oranice.Where(o => o.parcele.id == id).ToList();
            return View(parcele);
        }

        // GET: parcele/Create
        public ActionResult Create()
        {
            ViewBag.id_grada = new SelectList(db.gradovi, "id", "ime");
            return View();
        }

        // POST: parcele/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,koordinate,dimenzije,id_grada,lokacija,naziv")] parcele parcele)
        {

            parcele.id_korisnika = DobaviID();

            if (ModelState.IsValid)
            {
                db.parcele.Add(parcele);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_korisnika = new SelectList(db.gospodarstva, "id", "ime", parcele.id_korisnika);
            ViewBag.id_grada = new SelectList(db.gradovi, "id", "ime", parcele.id_grada);
            return View(parcele);
        }

        // GET: parcele/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            parcele parcele = db.parcele.Find(id);
            var userId = DobaviID();
            if (parcele == null || parcele.id_korisnika != userId)
            {
                return HttpNotFound();
            }
            ViewBag.id_korisnika = new SelectList(db.gospodarstva, "id", "ime", parcele.id_korisnika);
            ViewBag.id_grada = new SelectList(db.gradovi, "id", "ime", parcele.id_grada);
            return View(parcele);
        }

        // POST: parcele/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_korisnika,koordinate,dimenzije,id_grada,lokacija,naziv")] parcele parcele)
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(parcele).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.id_grada = new SelectList(db.gradovi, "id", "ime", parcele.id_grada);
            return View(parcele);
        }

        // GET: parcele/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            parcele parcele = db.parcele.Find(id);
            var userId = DobaviID();
            if (parcele == null || parcele.id_korisnika != userId)
            {
                return HttpNotFound();
            }
            return View(parcele);
        }

        // POST: parcele/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            parcele parcele = db.parcele.Find(id);
            try
            {
                db.parcele.Remove(parcele);
                db.SaveChanges();
            }
            catch
            {
                return View("Error");
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SPG/Views/parcele/Create.cshtml
@model SPG.parcele

@{
    ViewBag.Title = "Create";
}

<h2>Nova parcela</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.naziv, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.naziv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.naziv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.koordinate, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.koordinate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.koordinate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dimenzije, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dimenzije, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dimenzije, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_grada, "Grad", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_grada", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_grada, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lokacija, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lokacija, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lokacija, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Potvrdi" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SPG/Views/parcele/Delete.cshtml
@model SPG.parcele

@{
    ViewBag.Title = "Delete";
}

<h3>Jeste li sigurni da zelite izbrisati ovu parcelu ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt class="text-capitalize">
            @Html.DisplayNameFor(model => model.naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naziv)
        </dd>

        <dt class="text-capitalize">
            @Html.DisplayNameFor(model => model.koordinate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.koordinate)
        </dd>

        <dt class="text-capitalize">
            @Html.DisplayNameFor(model => model.dimenzije)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dimenzije)
        </dd>

        <dt>
            Grad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gradovi.ime)
        </dd>

        <dt class="text-capitalize">
            @Html.DisplayNameFor(model => model.lokacija)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lokacija)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
        </div>
    }
</div>

SPG/Views/parcele/Details.cshtml
@model SPG.parcele
@{
    ViewBag.Title = "Detalji";
    IEnumerable<farme> farme = ViewData["Farme"] as IEnumerable<farme>;
    IEnumerable<oranice> oranice = ViewData["Oranice"] as IEnumerable<oranice>;
}

<h2>Detalji o parceli</h2>

<div class="row">
    <div class="d-flex flex-column col-4 justify-content-start>
        <hr />
        <dl class="dl-horizontal">
            <dt class="text-capitalize">
                @Html.DisplayNameFor(model => model.naziv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.naziv)
            </dd>

            <dt class="text-capitalize">
                @Html.DisplayNameFor(model => model.koordinate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.koordinate)
            </dd>

            <dt class="text-capitalize">
                @Html.DisplayNameFor(model => model.dimenzije)
            </dt>

            <dd class="text-capitalize">
                @Html.DisplayFor(model => model.dimenzije)
            </dd>

            <dt>
                Grad
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gradovi.ime)
            </dd>

            <dt class="text-capitalize">
                @Html.DisplayNameFor(model => model.lokacija)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.lokacija)
            </dd>

        </dl>
   
    <p>
        @Html.ActionLink("Uredi", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Nazad na listu", "Index")
    </p>
</div>

<div class="d-flex flex-column col-8">
    <div>
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-farme-tab" data-toggle="pill" href="#pills-farme" role="tab" aria-controls="pills-farme" aria-selected="true">Farme</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-oranice-tab" data-toggle="pill" href="#pills-oranice" role="tab" aria-controls="pills-oranice" aria-selected="false">Oranice</a>
            </li>
        </ul>
    </div>

    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-farme" role="tabpanel" aria-labelledby="pills-farme-tab">
            <button class="btn btn-basic">
                @Html.ActionLink("Nova farma", "Create", new { controller = "farme", id = Model.id })
            </button>
                <table class="table">
                    <tr>
                        <th>
                            Naziv
                        </th>
                        <th>
                            Parcela
                        </th>
                        <th>
                            Akcije
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in farme)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.naziv)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.parcele.naziv)
                            </td>
                            <td>
                                @Html.ActionLink("Uredi", "Edit", new { id = item.id, controller = "farme" }) |
                                @Html.ActionLink("Detalji", "Details", new { id = item.id, controller = "farme" }) |
                                @Html.ActionLink("Izbriši", "Delete", new { id = item.id, controller = "farme" })
                            </td>
                        </tr>
                    }
                </table>
</div>

        <div class="tab-pane fade show" id="pills-oranice" role="tabpanel" aria-labelledby="pills-oranice-tab">
            <button class="btn btn-basic">
                @Html.ActionLink("Nova oranica", "Create", new { controller = "oranice", id = Model.id })
            </button>
            <table class="table">
                <tr>
                    <th>
                        Naziv
                    </th>
                    <th>
                        Parcela
                    </th>
                    <th>
                        Dimenzije
                    </th>
                    <th>
                        Stanje tla
                    </th>
                    <th>
                        Vrsta tla
                    </th>
                    <th>
                        Akcije
                    </th>
                </tr>
                @foreach (var item in oranice)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.parcele.naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.dimenzije)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.stanje_tla1.stanje)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.vrste_tla.vrsta)
                        </td>
                        <td>
                            @Html.ActionLink("Uredi", "Edit", new { id = item.id, controller = "oranice" }) |
                            @Html.ActionLink("Detalji", "Details", new { id = item.id, controller = "oranice" }) |
                            @Html.ActionLink("Izbriši", "Delete", new { id = item.id, controller = "oranice" })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

</div>

SPG/Views/parcele/Edit.cshtml
@model SPG.parcele

@{
    ViewBag.Title = "uredi parcelu";
}

<h2>Uredi parcelu</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.id_korisnika)
    <div class="form-group">
        @Html.LabelFor(model => model.naziv, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.naziv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.naziv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.koordinate, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.koordinate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.koordinate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dimenzije, htmlAttributes: new { @class = "control-label col-md-2  text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dimenzije, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dimenzije, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.id_grada, "Grad", htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.DropDownList("id_grada", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_grada, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lokacija, htmlAttributes: new { @class = "control-label col-md-2 text-capitalize" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lokacija, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lokacija, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SPG/Views/parcele/Index.cshtml
@{
    ViewBag.Title = "Parcele";
    IEnumerable<parcele> parcele = ViewData["Parcele"] as IEnumerable<parcele>;
    IEnumerable<farme> farme = ViewData["Farme"] as IEnumerable<farme>;
    IEnumerable<oranice> oranice = ViewData["Oranice"] as IEnumerable<oranice>;
}
<h2>Parcele</h2>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="pills-parcele-tab" data-toggle="pill" href="#pills-parcele" role="tab" aria-controls="pills-home" aria-selected="true">Parcele</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-farme-tab" data-toggle="pill" href="#pills-farme" role="tab" aria-controls="pills-profile" aria-selected="false">Farme</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-oranice-tab" data-toggle="pill" href="#pills-oranice" role="tab" aria-controls="pills-contact" aria-selected="false">Oranice</a>
    </li>
</ul>

<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-parcele" role="tabpanel" aria-labelledby="pills-parcele-tab">
        <button class="btn btn-basic">
            @Html.ActionLink("Nova parcela", "Create", "parcele")
        </button>
        <table class="table">
            <tr>
                <th>
                    Naziv
                </th>
                <th>
                    Koordinate
                </th>
                <th>
                    Dimenzije
                </th>
                <th>
                    Lokacija
                </th>
                <th>
                    Grad
                </th>
                <th>
                    Akcije
                </th>
            </tr>
            @foreach (var item in parcele)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.koordinate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dimenzije)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lokacija)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gradovi.ime)
                </td>
                <td>
                    @Html.ActionLink("Uredi", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Detalji", "Details", new { id = item.id }) |
                    @Html.ActionLink("Izbrisi", "Delete", new { id = item.id })
                </td>
            </tr>
            }
        </table>
    </div>
    <div class="tab-pane fade" id="pills-farme" role="tabpanel" aria-labelledby="pills-farme-tab">
        <button class="btn btn-basic">
            @Html.ActionLink("Nova farma", "Create", "farme")
        </button>
        <table class="table">
            <tr>
                <th>
                    Naziv
                </th>
                <th>
                    Parcela
                </th>
                <th>
                    Akcije
                </th>
            </tr>
            @foreach (var item in farme)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.parcele.naziv)
                </td>
                <td>
                    @Html.ActionLink("Uredi", "Edit", new { id = item.id, controller = "farme" }) |
                    @Html.ActionLink("Detalji", "Details", new { id = item.id, controller = "farme" }) |
                    @Html.ActionLink("Izbrisi", "Delete", new { id = item.id, controller = "farme" })
                </td>
            </tr>
            }
        </table>
    </div>
    <div class="tab-pane fade" id="pills-oranice" role="tabpanel" aria-labelledby="pills-oranice-tab">
        <button class="btn btn-basic">
            @Html.ActionLink("Nova oranica", "Create", "oranice")
        </button>
        <table class="table">
            <tr>
                <th>
                    Naziv
                </th>
                <th>
                    Parcela
                </th>
                <th>
                    Dimenzije
                </th>
                <th>
                    Stanje tla
                </th>
                <th>
                    Vrsta tla
                </th>
                <th>
                    Akcije
                </th>
            </tr>
            @foreach (var item in oranice)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.parcele.naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dimenzije)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.stanje_tla1.stanje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vrste_tla.vrsta)
                </td>
                <td>
                    @Html.ActionLink("Uredi", "Edit", new { id = item.id, controller = "oranice" }) |
                    @Html.ActionLink("Detalji", "Details", new { id = item.id, controller = "oranice" }) |
                    @Html.ActionLink("Izbrisi", "Delete", new { id = item.id, controller = "oranice" })
                </td>
            </tr>
            }
        </table>
    </div>
</div>